version: "3.8"

services:
  motor_telematics_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motor_telematics_frontend
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    # ensure dev server uses host 0.0.0.0 and port 8081
    command: npm run dev -- -H 0.0.0.0 -p 8081